# Generated by Django 4.0.3 on 2022-03-07 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_clothingtype_points_companymodel_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='clothingtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.clothingtype'),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.company'),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.size'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='clothingtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.clothingtype'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.user'),
        ),
    ]
